### ISSUE TITLE
duplicate value "may" in lv.php file

### ISSUE THREAD

**Issue by dzintars2** [jenssegers/date#299] opened 2018-07-02 18:52 UTC
In date language file lv.php there ar 2 values for "may". So long version of may name in latvian is incorrect.

**Comment by danhunsaker** [comment] 2018-07-02 19:49
Duplicate of #272

**Comment by jenssegers** [comment] 2018-07-03 07:43
Yes this is a known issue, but I still have yet to come up with a solution.

**Closed by jenssegers** 2018-07-03 07:43 UTC
